version: "3.8"
x-restart-policy: &restart_policy
  restart: on-failure
  deploy:
    restart_policy:
      condition: on-failure
x-redis: &redis
  <<: *restart_policy
  networks:
    - webnet
  environment:
    - SENTINEL_QUORUM=2
    - SENTINEL_DOWN_AFTER=1000
    - SENTINEL_FAILOVER=1000
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASS=pleasechangeme
    - REDIS_MASTER_NAME=${REDIS_MASTER_NAME:-redismaster}
    - REDIS_SENTINEL_IP=redis_sentinel
    - REDIS_SENTINEL_PORT=26379
    - REDIS_IP=${STACK:-redis-cluster-docker-swarm}_redis-zero

services:
  redis-sentinel:
    <<: *redis
    image: mlaradji/redis-sentinel:1.0.6
    ports:
      - "26379:26379"
    deploy:
      mode: global

  redis:
    <<: *redis
    image: mlaradji/redis-look:1.0.6
    ports:
      - "6379:6379"
    deploy:
      mode: global

  redis-zero:
    image: redis:6.0.8-alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: none
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: ""
