version: "3.8"
x-restart-policy: &restart_policy
  restart: on-failure
  deploy:
    restart_policy:
      condition: on-failure
x-redis: &redis
  <<: *restart_policy
  networks:
    - webnet
  environment:
    - SENTINEL_QUORUM=2
    - SENTINEL_DOWN_AFTER=1000
    - SENTINEL_FAILOVER=1000
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASS=pleasechangeme
    - REDIS_MASTER_NAME=${REDIS_MASTER_NAME:-redismaster}
    - REDIS_SENTINEL_IP=redis-sentinel
    - REDIS_SENTINEL_PORT=26379
    - REDIS_IP=${STACK:-redis-cluster-docker-swarm}_redis-zero
  secrets:
    - redis.crt
    - redis.key
    - ca.crt

services:
  redis-sentinel:
    <<: *redis
    image: mlaradji/redis-sentinel:1.0.7-redis6.0.8
    ports:
      - "26379:36379"
    deploy:
      mode: global
    # command:
    #   [
    #     "--tls-port",
    #     "36379",
    #     "--port",
    #     "26379",
    #     "--tls-replication",
    #     "no",
    #     "--tls-cert-file",
    #     "/run/secrets/redis.crt",
    #     "--tls-key-file",
    #     "/run/secrets/redis.key",
    #     "--tls-ca-cert-file",
    #     "/run/secrets/ca.crt",
    #   ]

  redis:
    <<: *redis
    image: mlaradji/redis-look:1.0.7-redis6.0.8
    ports:
      - "6379:56379"
    deploy:
      mode: global
    # command:
    #   [
    #     "--tls-port",
    #     "56379",
    #     "--port",
    #     "6379",
    #     "--tls-replication",
    #     "no",
    #     "--tls-cert-file",
    #     "/run/secrets/redis.crt",
    #     "--tls-key-file",
    #     "/run/secrets/redis.key",
    #     "--tls-ca-cert-file",
    #     "/run/secrets/ca.crt",
    #   ]

  redis-zero:
    image: redis:6.0.8-alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: none
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: ""

secrets:
  redis.crt:
    file: /certs/redis/redis.crt
  redis.key:
    file: /certs/redis/redis.key
  ca.crt:
    file: /certs/ca/ca.crt
