version: "3.1"

services:
  redis-master:
    image: redis:5.0.7-alpine
    deploy:
      replicas: 1

  redis-sentinel:
    image: mlaradji/redis-sentinel:${TAG:-latest}
    environment:
      - REDIS_IP=redis-master
      - REDIS_MASTER_NAME=redismaster
    deploy:
      replicas: 3

  redis:
    image: mlaradji/redis-look:${TAG:-latest}
    environment:
      - REDIS_SENTINEL_IP=redis-sentinel
      - REDIS_MASTER_NAME=redismaster
      - REDIS_SENTINEL_PORT=26379
    deploy:
      replicas: 3
